// DEMO DATA — simulates rows from the future `alerts` table, generated by
// the monitoring + AI-analysis pipeline. Structure matches the Alert type.
import type { Alert } from "../types";

export const mockAlerts: Alert[] = [
  {
    id: "alert_001",
    competitorId: "comp_001",
    competitorName: "Brightline SaaS",
    type: "price_change",
    importance: "high",
    title: "Price change detected",
    detectedAt: "2026-08-16T07:15:00Z",
    summary: "Brightline increased their Pro plan from €29/month to €39/month.",
    aiInsight:
      "The competitor appears to be repositioning this plan toward a more premium price point. This often signals added features or a shift toward higher-value customers.",
    details: [{ label: "Pro plan", before: "€29/month", after: "€39/month" }],
    changePercentage: 34,
    read: false,
  },
  {
    id: "alert_002",
    competitorId: "comp_002",
    competitorName: "Flowmetric",
    type: "new_service",
    importance: "high",
    title: "New service launched",
    detectedAt: "2026-08-15T18:40:00Z",
    summary: "Flowmetric added a new \"Flowmetric for Agencies\" service tier.",
    aiInsight:
      "This looks like an expansion into the agency segment, a market they haven't targeted before. Worth watching if they start marketing it to your existing customers.",
    details: [{ label: "New offering", after: "Flowmetric for Agencies" }],
    read: false,
  },
  {
    id: "alert_003",
    competitorId: "comp_003",
    competitorName: "Ledgerly",
    type: "promotion",
    importance: "medium",
    title: "Promotion detected",
    detectedAt: "2026-08-14T09:32:00Z",
    summary: "Ledgerly launched a \"3 months free\" promotion for annual plans.",
    aiInsight:
      "This is likely a push to boost annual sign-ups before quarter end. Consider whether a limited-time offer of your own would help retain price-sensitive prospects.",
    details: [{ label: "Offer", after: "3 months free on annual plans" }],
    read: true,
  },
  {
    id: "alert_004",
    competitorId: "comp_001",
    competitorName: "Brightline SaaS",
    type: "product_change",
    importance: "medium",
    title: "Product change detected",
    detectedAt: "2026-08-13T11:05:00Z",
    summary: "Brightline removed \"Custom Integrations\" from their Starter plan.",
    aiInsight:
      "Feature removal from an entry plan usually pushes customers to upgrade. This could be an opportunity to highlight your own inclusive integrations.",
    details: [{ label: "Starter plan", before: "Includes custom integrations", after: "Custom integrations removed" }],
    read: true,
  },
  {
    id: "alert_005",
    competitorId: "comp_002",
    competitorName: "Flowmetric",
    type: "content_change",
    importance: "low",
    title: "Website content updated",
    detectedAt: "2026-08-12T15:20:00Z",
    summary: "Flowmetric rewrote their homepage headline and hero copy.",
    aiInsight:
      "The new messaging leans more heavily on automation and speed, a shift from their previous focus on collaboration. This may reflect a broader positioning change.",
    details: [
      { label: "Old headline", before: "Work better, together." },
      { label: "New headline", after: "Automate the busywork." },
    ],
    read: true,
  },
  {
    id: "alert_006",
    competitorId: "comp_001",
    competitorName: "Brightline SaaS",
    type: "price_change",
    importance: "low",
    title: "Minor pricing update",
    detectedAt: "2026-08-10T08:00:00Z",
    summary: "Brightline adjusted their annual discount from 20% to 15%.",
    aiInsight:
      "A smaller annual discount can mean healthier margins or less pressure to hit growth targets through annual pre-payment.",
    details: [{ label: "Annual discount", before: "20% off", after: "15% off" }],
    changePercentage: -5,
    read: true,
  },
];
